"""add last_notified_at to habits

Revision ID: b86967f70f32
Revises: 4b8c9d2e1f3a
Create Date: 2026-08-09 01:38:39.201801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b86967f70f32'
down_revision: Union[str, None] = '4b8c9d2e1f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'last_notified_at')
    # ### end Alembic commands ###
